jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List repository files
        run: ls -R

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push CV Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./cv  # Adjust the path if needed
          push: true
          tags: raidlol/cv-server:latest
          
      - name: Build and push LLM Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./llm  # Adjust the path if needed
          push: true
          tags: raidlol/llm-server:latest
